### ISSUE TITLE
Is it possible to show google PROMPT?

### ISSUE THREAD

**Issue by gvlamadrid** [de-code/react-native-android-speech-recognizer#3]
I need to show PROMPT but couldn't pass params startListening on recognizerIntentParameters. 
Any idea?
Txs!

**Comment by de-code** [comment]
Have you tried the EXTRA_PROMPT parameter? https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_PROMPT

**Comment by gvlamadrid** [comment]
I try... but nothing happen. I think, I'm passing parameter in an incorrect way. 
`recognizer.startListening(RecognizerIntent.ACTION_RECOGNIZE_SPEECH, { "EXTRA_PROMPT":"Say fast" });`

**Comment by de-code** [comment]
I don't know what the actual value to pass in is. I'd use the constant instead, e.g.:
```js
recognizer.startListening(
  RecognizerIntent.ACTION_RECOGNIZE_SPEECH, {
    [RecognizerIntent.EXTRA_PROMPT]: 'Say something'
  }
);
```

That way it will use the value of the constant `RecognizerIntent.EXTRA_PROMPT` as the key.
I haven't tested it myself but that is the intended way to pass in parameters (see example using EXTRA_PARTIAL_RESULTS).

**Comment by de-code** [comment]
If you actually want to show the regular prompt, then you may be interested in an alternative component: https://github.com/wenkesj/react-native-voice

**Comment by gvlamadrid** [comment]
txs! I modified the app to use this.
