### ISSUE TITLE
Set language for recognizer?

### ISSUE THREAD

**Issue by MrHazimAli** [de-code/react-native-android-speech-recognizer#4]
Hye,
Im interested to use this package to create something for arabic language, I would like to know how to set this to recognize speech in arabic and other language as well.

Thanks!

**Comment by de-code** [comment]
Hi, [RecognizerIntent](https://developer.android.com/reference/android/speech/RecognizerIntent.html) includes a [EXTRA_LANGUAGE](https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_LANGUAGE) field that you can set when calling `startListening`.

**Comment by MrHazimAli** [comment]
@de-code , oh.. I misslook this part.. thanks! it's working 👍
