### ISSUE TITLE
offline support ?

### ISSUE THREAD

**Issue by MrHazimAli** [de-code/react-native-android-speech-recognizer#5]
Hye,
I was wondering do this library supported during offline ?

**Comment by de-code** [comment]
Hi,

This library is only a thin wrapper around Google's Speech API. Therefore it depends on whether Google's Android Speech API supports offline mode.

This would suggest that it does but I haven't tried it myself:
https://stackoverflow.com/questions/17616994/offline-speech-recognition-in-android-jellybean

There is also a flag to prefer offline speech:
https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_PREFER_OFFLINE

**Comment by MrHazimAli** [comment]
Hi,
thanks for fast response. 
I see. alright, will look more into the flag to prefer whether it's working or no.
I really like this package as it reduce the amount of work yet working flawlessly rather than other package available in my opinion.

Thanks for creating it and have a nice day! 😄
